modified init script to load image from gcp.

diff --git a/bin/coreos-install b/bin/coreos-install
--- a/bin/coreos-install
+++ b/bin/coreos-install
@@ -47,9 +47,7 @@ done
 USAGE="Usage: $0 -d <device> [options]
 Options:
     -d DEVICE   Install Container Linux to the given device.
-    -V VERSION  Version to install (e.g. current) [default: ${VERSION_ID}].
-    -B BOARD    Container Linux board to use [default: ${BOARD}].
-    -C CHANNEL  Release channel to use (e.g. beta) [default: ${CHANNEL_ID}].
+    -V VERSION  Version to install (e.g. current) [default: current].
     -o OEM      OEM type to install (e.g. ami) [default: ${OEM_ID:-(none)}].
     -c CLOUD    Insert a cloud-init config to be executed on boot.
     -i IGNITION Insert an Ignition config to be executed on boot.
@@ -364,6 +362,8 @@ CLOUDINIT=
 IMAGE_FILE=
 KEYFILE=
 VERSION_SUMMARY='CoreOS Container Linux'
+BASE_URL=https://storage.googleapis.com/mediadepot-coreos/boards/amd64-usr
+VERSION_ID='current'
 
 while getopts "V:B:C:d:o:c:i:t:b:k:f:nyvh" OPTION
 do
@@ -529,41 +529,41 @@ function install_from_url() {
     fi
 
     local IMAGE_URL="${BASE_URL}/${VERSION_ID}/${IMAGE_NAME}"
-    local SIG_NAME="${IMAGE_NAME}.sig"
-    local SIG_URL="${BASE_URL}/${VERSION_ID}/${SIG_NAME}"
+#    local SIG_NAME="${IMAGE_NAME}.sig"
+#    local SIG_URL="${BASE_URL}/${VERSION_ID}/${SIG_NAME}"
 
     if ! wget --spider --quiet "${IMAGE_URL}"; then
         echo "$0: Image URL unavailable: $IMAGE_URL" >&2
         exit 1
     fi
 
-    if ! wget --spider --quiet "${SIG_URL}"; then
-        echo "$0: Image signature unavailable: $SIG_URL" >&2
-        exit 1
-    fi
+#    if ! wget --spider --quiet "${SIG_URL}"; then
+#        echo "$0: Image signature unavailable: $SIG_URL" >&2
+#        exit 1
+#    fi
 
-    # Setup GnuPG for verifying the image signature
-    export GNUPGHOME="${WORKDIR}/gnupg"
-    mkdir -p "${GNUPGHOME}"
-    if [ -n "${KEYFILE}" ]; then
-        gpg --batch --quiet --import < "${KEYFILE}"
-    else
-        gpg --batch --quiet --import <<< "${GPG_KEY}"
-    fi
-
-    echo "Downloading the signature for ${IMAGE_URL}..."
-    wget --no-verbose -O "${WORKDIR}/${SIG_NAME}" "${SIG_URL}"
+#    # Setup GnuPG for verifying the image signature
+#    export GNUPGHOME="${WORKDIR}/gnupg"
+#    mkdir -p "${GNUPGHOME}"
+#    if [ -n "${KEYFILE}" ]; then
+#        gpg --batch --quiet --import < "${KEYFILE}"
+#    else
+#        gpg --batch --quiet --import <<< "${GPG_KEY}"
+#    fi
+#
+#    echo "Downloading the signature for ${IMAGE_URL}..."
+#    wget --no-verbose -O "${WORKDIR}/${SIG_NAME}" "${SIG_URL}"
 
     echo "Downloading, writing and verifying ${IMAGE_NAME}..."
     if ! wget --no-verbose -O - "${IMAGE_URL}" \
-        | tee >(bzip2 -cd >&3) \
-        | gpg --batch --trusted-key "${GPG_LONG_ID}" \
-            --verify "${WORKDIR}/${SIG_NAME}" -
+        | bzip2 -cd >&3
+#        | gpg --batch --trusted-key "${GPG_LONG_ID}" \
+#            --verify "${WORKDIR}/${SIG_NAME}" -
     then
         local EEND=( "${PIPESTATUS[@]}" )
         [ ${EEND[0]} -ne 0 ] && echo "${EEND[0]}: Download of ${IMAGE_NAME} did not complete" >&2
         [ ${EEND[1]} -ne 0 ] && echo "${EEND[1]}: Cannot expand ${IMAGE_NAME} to ${DEVICE}" >&2
-        [ ${EEND[2]} -ne 0 ] && echo "${EEND[2]}: GPG signature verification failed for ${IMAGE_NAME}" >&2
+#        [ ${EEND[2]} -ne 0 ] && echo "${EEND[2]}: GPG signature verification failed for ${IMAGE_NAME}" >&2
         exit 1
     fi 3> >(write_to_disk)
 
